name: Upgrade Plugins
on:
  push:
    branches: main
    tags:
      - v*.*.* # a new version of rua is released

jobs:
  build:
    if: ${{ !endsWith(github.event.push.ref, "0") }} # this release is a new minor version
    runs-on: ubuntu-latest
    steps:
      # setup env
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: retrieve tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> tee $GITHUB_ENV
      - name: setup git
        run: |
          git config user.name 'DiscreteTom'
          git config user.email 'discrete_tom@outlook.com'
          git checkout -b auto-upgrade-plugins-${{ TAG }}

      # upgrade plugins
      - name: upgrade kcp plugin
        working-directory: ./rua/plugin/network/kcp
        run: |
          go get github.com/DiscreteTom/rua@${TAG}
          go mod tidy
      - name: upgrade websocket plugin
        working-directory: ./rua/plugin/network/websocket
        run: |
          go get github.com/DiscreteTom/rua@${TAG}
          go mod tidy
      - name: upgrade kinesis plugin
        working-directory: ./rua/plugin/stream/kinesis
        run: |
          go get github.com/DiscreteTom/rua@${TAG}
          go mod tidy
      # - name: setup git commit & tags
      #   run: |
      #     git commit -m "auto upgrade plugins"
      #     for PLUGIN_NAME in plugin/network/kcp plugin/network/websocket plugin/stream/kinesis
      #     do
      #       OLD_VERSION=`git tag -l "${PLUGIN_NAME}/*" --sort=-version:refname | head -n 1`
      #       NEW_VERSION=`echo $OLD_VERSION | awk -F. -v OFS=. '{$NF++;print}'`
      #       git tag -a ${NEW_VERSION}
      #     done

      # create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-upgrade-plugins-${{ TAG }}
          token: PersonalAccessToken
